name: CI
on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.REMOTE_KEY }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          rm -rf ~/www.jittagornp.me/dist 
          cd ~/www.jittagornp.me && git pull
